# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'FaceTraking' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FaceTraking
  pod 'BubbleTransition', '~> 2.0.0'

  pod 'SquishButton'

  pod 'Spring', :git => 'https://github.com/MengTo/Spring.git'

  target 'FaceTrakingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FaceTrakingUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
